services:
  azfin-backend:
    volumes:
      - ./datastore/uploads:/app/uploads
    ports:
      - "3002:3001"

  azfin-frontend:
    ports:
      - "901:901"

networks:
  edge:
    external: false
    name: azfin-local-edge
